"""
Reconstruct rotation_high_050 in three variants using precomputed skyseg masks.

Expected input:
  outputs/renders/vggt-omega/ego4d/skyseg/<clip_name>/
    images/frame_000001.jpg ...
    sky_masks/frame_000001.jpg ...
    sky_masks_strict/frame_000001.jpg ...

The sky masks generated by visual_util.segment_sky are keep-masks:
  sky pixels:     0
  non-sky pixels: 255

This script runs VGGT-Omega once on images/, then writes:
  original/scene.ply
  sky_mask/scene.ply
  strict_sky_glare_mask/scene.ply
"""

from __future__ import annotations

import argparse
import glob
import json
import os

import numpy as np


PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.."))
CLIP_NAME = "rotation_high_050__dc708402-b918-4bef-b2ea-88bf22a7fb1f"
DEFAULT_SKYSEG_DIR = os.path.join(
    PROJECT_ROOT,
    "outputs/renders/vggt-omega/ego4d/skyseg",
    CLIP_NAME,
)
DEFAULT_OUTPUT_DIR = os.path.join(
    PROJECT_ROOT,
    "outputs/renders/vggt-omega/ego4d/skyseg_reconstruction",
    CLIP_NAME,
)
DEFAULT_FPS = 6.0


def image_paths(image_dir: str) -> list[str]:
    return sorted(
        p
        for p in glob.glob(os.path.join(image_dir, "*"))
        if os.path.splitext(p)[1].lower() in (".jpg", ".jpeg", ".png")
    )


def save_metadata(
    save_path: str,
    mode: str,
    skyseg_dir: str,
    image_dir: str,
    mask_dir: str | None,
    output_dir: str,
    num_images: int,
    fps: float,
    image_resolution: int,
    checkpoint: str,
) -> None:
    metadata = {
        "mode": mode,
        "clip_name": CLIP_NAME,
        "skyseg_dir": skyseg_dir,
        "image_dir": image_dir,
        "mask_dir": mask_dir,
        "output_dir": output_dir,
        "num_images": num_images,
        "fps_for_pose_timestamps": fps,
        "image_resolution": image_resolution,
        "checkpoint": checkpoint,
        "sky_mask_convention": "sky=0, non_sky=255",
    }
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)
    print(f"  Saved: {save_path}")


def apply_keep_masks(conf: np.ndarray, image_names: list[str], mask_dir: str) -> np.ndarray:
    import cv2

    height, width = conf.shape[-2:]
    masks = []
    for image_name in image_names:
        mask_path = os.path.join(mask_dir, image_name)
        if not os.path.exists(mask_path):
            raise FileNotFoundError(mask_path)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        if mask is None:
            raise ValueError(f"Could not read mask: {mask_path}")
        if mask.shape != (height, width):
            mask = cv2.resize(mask, (width, height), interpolation=cv2.INTER_NEAREST)
        masks.append(mask)
    return conf * (np.asarray(masks) > 0.1).astype(np.float32)


def save_reconstruction_variant(
    reconstruction,
    predictions: dict,
    output_dir: str,
    mode: str,
    skyseg_dir: str,
    image_dir: str,
    mask_dir: str | None,
    image_names: list[str],
    num_images: int,
    fps: float,
    checkpoint: str,
) -> None:
    os.makedirs(output_dir, exist_ok=True)
    variant_predictions = dict(predictions)
    if mask_dir is not None:
        print(f"Applying {mode} mask to depth confidence ...")
        variant_predictions["depth_conf"] = apply_keep_masks(
            predictions["depth_conf"],
            image_names,
            mask_dir,
        )

    print(f"Saving {mode} reconstruction outputs ...")
    reconstruction.save_trajectory_png(
        variant_predictions["extrinsic"],
        os.path.join(output_dir, "camera_trajectory.png"),
    )
    reconstruction.save_prediction_pose(
        variant_predictions,
        os.path.join(output_dir, "predictions_pose.npz"),
        start_sec=0.0,
        fps=fps,
    )
    reconstruction.save_ply(variant_predictions, os.path.join(output_dir, "scene.ply"))
    save_metadata(
        os.path.join(output_dir, "metadata.json"),
        mode=mode,
        skyseg_dir=skyseg_dir,
        image_dir=image_dir,
        mask_dir=mask_dir,
        output_dir=output_dir,
        num_images=num_images,
        fps=fps,
        image_resolution=reconstruction.IMAGE_RES,
        checkpoint=checkpoint,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skyseg-dir", default=DEFAULT_SKYSEG_DIR)
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--checkpoint", help="VGGT-Omega checkpoint path")
    parser.add_argument("--fps", type=float, default=DEFAULT_FPS)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    image_dir = os.path.join(args.skyseg_dir, "images")
    mask_dir = os.path.join(args.skyseg_dir, "sky_masks")
    strict_mask_dir = os.path.join(args.skyseg_dir, "sky_masks_strict")

    if not os.path.isdir(image_dir):
        raise FileNotFoundError(f"Missing skyseg images directory: {image_dir}")
    if not os.path.isdir(mask_dir):
        raise FileNotFoundError(f"Missing skyseg masks directory: {mask_dir}")
    if not os.path.isdir(strict_mask_dir):
        raise FileNotFoundError(
            f"Missing strict skyseg masks directory: {strict_mask_dir}. "
            "Run segment_high050_sky.py --overwrite first."
        )

    paths = image_paths(image_dir)
    if len(paths) < 2:
        raise ValueError(f"Need at least 2 images, got {len(paths)} in {image_dir}")

    expected_outputs = [
        os.path.join(args.output_dir, "original", "scene.ply"),
        os.path.join(args.output_dir, "sky_mask", "scene.ply"),
        os.path.join(args.output_dir, "strict_sky_glare_mask", "scene.ply"),
    ]
    if all(os.path.exists(path) for path in expected_outputs) and not args.overwrite:
        print(f"Already done, skipping: {args.output_dir}")
        return

    import reconstruction

    if args.checkpoint is None:
        args.checkpoint = reconstruction.CHECKPOINT

    os.makedirs(args.output_dir, exist_ok=True)
    print(f"Found {len(paths)} skyseg images under {image_dir}")
    print(f"Using sky masks under {mask_dir}")
    print(f"Using strict sky/glare masks under {strict_mask_dir}")
    print(f"Loading model from {args.checkpoint}")
    model = reconstruction.load_model(args.checkpoint)
    print("Model loaded.")

    print("Running inference ...")
    predictions = reconstruction.run_inference(image_dir, model)
    image_names = [os.path.basename(path) for path in paths]

    save_reconstruction_variant(
        reconstruction,
        predictions,
        output_dir=os.path.join(args.output_dir, "original"),
        mode="original",
        skyseg_dir=args.skyseg_dir,
        image_dir=image_dir,
        mask_dir=None,
        image_names=image_names,
        num_images=len(paths),
        fps=args.fps,
        checkpoint=args.checkpoint,
    )
    save_reconstruction_variant(
        reconstruction,
        predictions,
        output_dir=os.path.join(args.output_dir, "sky_mask"),
        mode="sky_mask",
        skyseg_dir=args.skyseg_dir,
        image_dir=image_dir,
        mask_dir=mask_dir,
        image_names=image_names,
        num_images=len(paths),
        fps=args.fps,
        checkpoint=args.checkpoint,
    )
    save_reconstruction_variant(
        reconstruction,
        predictions,
        output_dir=os.path.join(args.output_dir, "strict_sky_glare_mask"),
        mode="strict_sky_glare_mask",
        skyseg_dir=args.skyseg_dir,
        image_dir=image_dir,
        mask_dir=strict_mask_dir,
        image_names=image_names,
        num_images=len(paths),
        fps=args.fps,
        checkpoint=args.checkpoint,
    )
    print("All done.")


if __name__ == "__main__":
    main()
